---
title: Class Diagram for HR Service and Workflow Service
---
classDiagram

    class HRService{
        <<Service>>
        -HRRepo repo
        -WorkflowService workflow
        -Logger logger
    }

    class WorkflowService{

    }

    HRService *-- HRRepo: has a
    HRService *-- WorkflowService: has a
    HRService *-- Logger: has a
